In [2]:
# import libreries
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
# varaibles
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([1,5,10,14,24,36,50,66,90])


In [5]:
# 1D to 2D
x = x.reshape((-1,1))
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
# create a model
model = LinearRegression()

# fit the model
model.fit(x,y)

LinearRegression()

In [9]:
# R square score(coefficient)
model.score(x,y)

0.9235494650403093

In [10]:
# y intercept
model.intercept_

-20.527777777777793

In [11]:
# coef
model.coef_

array([10.68333333])

In [15]:
# y predict
y_pred = model.predict(x)
print(y)
print(y_pred)

[ 1  5 10 14 24 36 50 66 90]
[-9.84444444  0.83888889 11.52222222 22.20555556 32.88888889 43.57222222
 54.25555556 64.93888889 75.62222222]


In [18]:
# mean squared error
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y,y_pred)
mse

62.98580246913577

In [21]:
rmse = mean_squared_error(y,y_pred, squared=False)
rmse


7.936359522421837

In [22]:
# R squared 
from sklearn.metrics import r2_score
r2_score(y, y_pred)

0.9235494650403093